spring:
  application:
    name: scanity

  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/dev_test}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

minio:
  endpoint: ${S3_ENDPOINT:http://localhost:9000}
  bucket: ${S3_BUCKET:scanity-s3-dev}
  region: ${S3_REGION:ru-central1}

  access-key: ${S3_ACCESS_KEY:minioadmin}
  secret-key: ${S3_SECRET_KEY:minioadmin}